pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Java Application') {
            steps {
                dir('app') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Archive Build Artifact') {
            steps {
                archiveArtifacts artifacts: 'app/target/*.jar', fingerprint: true
            }
        }
    }

    post {
        success {
            echo "Build completed successfully!"
        }

        failure {
            echo "Build failed!"
        }

        always {
            echo "Pipeline execution finished."
        }
    }
}